# Generated by Django 5.2.2 on 2025-06-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmc_proxy', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cmcmarketdata',
            index=models.Index(condition=models.Q(('market_cap__gt', 0), ('market_cap__isnull', False)), fields=['-market_cap'], name='cmc_mktdata_cap_desc_idx'),
        ),
    ]
