# Generated by Django 5.2.2 on 2025-07-27 17:26

import common.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmc_proxy', '0002_cmcmarketdata_cmc_mktdata_cap_desc_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmckline',
            name='volume',
            field=common.model_fields.DecField(blank=True, decimal_places=8, max_digits=40, null=True),
        ),
    ]
