# Generated by Django 5.2.2 on 2025-07-19 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmc_proxy', '0002_cmcmarketdata_cmc_mktdata_cap_desc_idx'),
        ('price_oracle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetprice',
            name='cmc_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_prices', to='cmc_proxy.cmcasset', verbose_name='CMC资产关联'),
        ),
    ]
